# Generated by Django 5.2 on 2025-06-04 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_to_group_model', to='structure.sciencegroup'),
        ),
        migrations.AddField(
            model_name='lessonsource',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessonsource_to_lesson', to='main.lesson'),
        ),
        migrations.AddField(
            model_name='lessonsource',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessonsource_to_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nb',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nb_to_lesson', to='main.lesson'),
        ),
        migrations.AddField(
            model_name='nb',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nb_to_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingnotebook',
            name='science_name',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_plans', to='structure.science'),
        ),
        migrations.AddField(
            model_name='ratingnotebook',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratingnotebook_to_semester', to='structure.academicyear'),
        ),
        migrations.AddField(
            model_name='ratingnotebook',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratingnotebook_to_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_to_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_to_group', to='structure.sciencegroup'),
        ),
        migrations.AddField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_to_lesson', to='main.lesson'),
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_to_task', to='main.task'),
        ),
    ]
