# Generated by Django 5.2 on 2025-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('dekan', 'Dekan'), ('dirrector', 'Dirrector'), ('department_user', 'Department User'), ('tutor', 'Tutor'), ('stylist', 'Stylist'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=50, unique=True, verbose_name='Role Name'),
        ),
    ]
